# -*- coding: utf-8 -*-
"""Project Machine Learning - Online Retail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Co1vPBtIjHFp001t85JjnWGCeHFQxxo8
"""

import numpy as np
import pandas as pd
import os

# read file
path = 'online_retail_II.csv'
data = pd.read_csv(path)
print("Data Describe ===========================")
print(data.describe())
print("=========================================")

data.isnull().sum()

data.info()

pd.set_option("display.max_rows", 101)
pd.set_option("display.max_columns", 10)
negprice = data[data['Price'] < 0].sum()
negquantity = data[data['Quantity'] < 0].count()

np.set_printoptions(threshold=np.inf)
data['Description'].unique()

df_new = data['Description']
df_new = df_new.dropna()
df_new.dropna()
df_new = pd.DataFrame(df_new)


my_list = [y for x in df_new['Description'] for y in x.split() if y.islower()]
mylist = list(set(my_list))
mylist

##menghapus data yang tidak sesuai
data_bad = data[data['Description'].isin([ mylist ])]

data = data[~data.apply(tuple,1).isin(data_bad.apply(tuple,1))]

##mengubah data null menjadi 99999
data[['Customer ID']] =data[['Customer ID']].fillna(99999)
#replace null description values with 'Unknown'
data[['Description']] =data[['Description']].fillna('Unknown')

##menghapus data dengan pembelian negatif dan ID customer yang tidak sesuai
data = data[data['Quantity'] > 0]
data = data[data['Customer ID'] != 99999]
##menghapus data pengembalian barang
data = data[~data["Invoice"].str.contains("C", na = False)]

data.info()

data = data.drop_duplicates()
data.shape